/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#09151a',
        surface: '#09151a',
        'surface-dim': '#09151a',
        'surface-bright': '#2f3b40',
        'surface-container-lowest': '#041015',
        'surface-container-low': '#111d22',
        'surface-container': '#152126',
        'surface-container-high': '#202c31',
        'surface-container-highest': '#2a373c',
        'surface-variant': '#2a373c',
        'surface-tint': '#6be026',
        'card-dark': '#1b2e35',
        'card-border': '#2b4754',
        'on-surface': '#d7e5eb',
        'on-surface-variant': '#becbb1',
        'inverse-surface': '#d7e5eb',
        'inverse-on-surface': '#263237',
        outline: '#88957d',
        'outline-variant': '#3f4a36',
        primary: '#74e930',
        'on-primary': '#133800',
        'primary-container': '#58cc02',
        'on-primary-container': '#1e5000',
        'primary-fixed': '#87fe45',
        'primary-fixed-dim': '#6be026',
        'on-primary-fixed': '#082100',
        'on-primary-fixed-variant': '#1f5100',
        'ecto-green-dark': '#46a302',
        secondary: '#88ceff',
        'on-secondary': '#00344d',
        'secondary-container': '#00a8ed',
        'on-secondary-container': '#003954',
        'secondary-fixed': '#c8e6ff',
        'secondary-fixed-dim': '#88ceff',
        'on-secondary-fixed': '#001e2e',
        'on-secondary-fixed-variant': '#004c6e',
        'macaw-blue-dark': '#1899d6',
        tertiary: '#fec800',
        'on-tertiary': '#3e2e00',
        'tertiary-container': '#ddad00',
        'on-tertiary-container': '#574300',
        'lightning-gold': '#ffc800',
        'tertiary-fixed': '#ffdf92',
        'tertiary-fixed-dim': '#f4bf00',
        'crimson-heart': '#ff4b4b',
        'crimson-heart-dark': '#d92f2f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'text-muted': '#89a3af',
        'gray-inactive': '#37464f',
        'gray-inactive-dark': '#242e34',
      },
      fontFamily: {
        sans: ['Nunito Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      },
    },
  },
  plugins: [],
};
